-- GulfDeals — Supabase PostgreSQL Schema (v2)
-- Run this in Supabase SQL Editor: Dashboard → SQL Editor → New query
-- Schema v2 adds: seller_name, seller_rating, feature_bullets, tech_specs_raw

-- ─── EXTENSIONS ──────────────────────────────────────────────────────────────
create extension if not exists "uuid-ossp";
create extension if not exists "pg_cron";

-- ─── PRODUCTS ─────────────────────────────────────────────────────────────────
create table if not exists products (
  id              uuid primary key default uuid_generate_v4(),

  -- Classification
  category        text not null check (category in ('laptop','cpu','gpu','ram','ssd','monitor')),
  brand           text not null,
  model           text not null,

  -- Retailer
  retailer        text not null check (retailer in ('amazon_ae','noon','sharaf_dg','emax','virgin')),
  retailer_id     text,                             -- retailer's own product/ASIN/SKU
  product_url     text not null,
  affiliate_url   text,
  image_url       text,

  -- Pricing
  current_price   numeric(10,2) not null,
  original_price  numeric(10,2),
  discount_pct    numeric(5,2) generated always as (
                    case when original_price > 0 and original_price > current_price
                    then round(((original_price - current_price) / original_price) * 100, 2)
                    else 0 end
                  ) stored,

  -- Structured specs — flexible JSONB for all category-specific fields
  -- GPU example:  { "gpu_chip": "RTX 4090", "vram_gb": 24, "vram_type": "GDDR6X",
  --                 "cuda_cores": 16384, "boost_clock_mhz": 2520, "tdp_watts": 450 }
  -- CPU example:  { "cpu_brand": "Intel", "cpu_model": "Core i9-14900K",
  --                 "cores": 24, "threads": 32, "boost_clock_ghz": 6.0,
  --                 "tdp_watts": 125, "socket": "LGA1700", "l3_cache_mb": 36 }
  -- Laptop example: { "screen_size_inch": 16, "refresh_rate_hz": 240,
  --                   "cpu_model": "Core i9-14900HX", "gpu_model": "RTX 4090",
  --                   "ram_gb": 32, "storage_gb": 2000 }
  specs           jsonb default '{}',

  -- Raw data for debugging / re-processing
  tech_specs_raw  jsonb default '{}',               -- raw key/value table from product page
  feature_bullets text[],                           -- product bullet points from listing

  -- Searchable tags generated by spec_parser
  tags            text[] default '{}',

  -- Seller info (scraped from product page)
  seller_name     text,
  seller_rating   numeric(5,2),                     -- % positive ratings (Amazon) or 1-5 (Noon)

  -- Availability & quality signals
  is_available    boolean default true,
  is_hot          boolean default false,            -- auto-set by trigger

  -- Ratings
  rating          numeric(3,1),
  review_count    int default 0,

  -- Timestamps
  last_scraped    timestamptz,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now(),

  unique (retailer, retailer_id)                    -- prevent duplicate listings
);

-- ─── INDEXES ──────────────────────────────────────────────────────────────────
create index if not exists idx_products_category     on products(category);
create index if not exists idx_products_retailer     on products(retailer);
create index if not exists idx_products_brand        on products(brand);
create index if not exists idx_products_price        on products(current_price);
create index if not exists idx_products_discount     on products(discount_pct desc) where is_available = true;
create index if not exists idx_products_rating       on products(rating desc nulls last);
create index if not exists idx_products_hot          on products(is_hot) where is_hot = true;
create index if not exists idx_products_last_scraped on products(last_scraped desc);
-- GIN index for specs JSONB queries (e.g. products where specs->>'gpu_chip' = 'RTX 4090')
create index if not exists idx_products_specs        on products using gin(specs);
-- GIN index for tags array (e.g. products where 'RTX 4090' = ANY(tags))
create index if not exists idx_products_tags         on products using gin(tags);

-- ─── TRIGGERS — updated_at ────────────────────────────────────────────────────
create or replace function update_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_updated_at on products;
create trigger products_updated_at
  before update on products
  for each row execute function update_updated_at();

-- ─── TRIGGERS — is_hot ────────────────────────────────────────────────────────
-- A deal is "hot" when: discount >= 20%, rating >= 4.3, and currently available
create or replace function refresh_is_hot()
returns trigger language plpgsql as $$
begin
  new.is_hot := (
    new.discount_pct >= 20
    and coalesce(new.rating, 0) >= 4.3
    and new.is_available = true
  );
  return new;
end;
$$;

drop trigger if exists products_is_hot on products;
create trigger products_is_hot
  before insert or update on products
  for each row execute function refresh_is_hot();

-- ─── PRICE HISTORY ────────────────────────────────────────────────────────────
create table if not exists price_history (
  id          bigserial primary key,
  product_id  uuid not null references products(id) on delete cascade,
  price       numeric(10,2) not null,
  retailer    text not null,
  scraped_at  timestamptz default now()
);

create index if not exists idx_price_history_product_time
  on price_history(product_id, scraped_at desc);

-- Only insert a new price_history row when the price actually changed
create or replace function insert_price_if_changed()
returns trigger language plpgsql as $$
declare
  last_price numeric;
begin
  select price into last_price
  from price_history
  where product_id = new.id
  order by scraped_at desc
  limit 1;

  if last_price is distinct from new.current_price then
    insert into price_history(product_id, price, retailer)
    values (new.id, new.current_price, new.retailer);
  end if;
  return new;
end;
$$;

drop trigger if exists products_price_history on products;
create trigger products_price_history
  after insert or update of current_price on products
  for each row execute function insert_price_if_changed();

-- ─── ALERTS (user subscriptions) ─────────────────────────────────────────────
create table if not exists alerts (
  id            uuid primary key default uuid_generate_v4(),
  product_id    uuid references products(id) on delete cascade,  -- null = "any new deal"
  channel       text not null check (channel in ('email','whatsapp')),
  destination   text not null,                    -- email or E.164 phone e.g. +971501234567
  target_price  numeric(10,2),                    -- notify when price ≤ this; null = any drop
  alert_type    text not null default 'price_drop'
                  check (alert_type in ('price_drop','any_change','new_deal')),
  active        boolean default true,
  token         uuid default uuid_generate_v4(),  -- for unsubscribe link
  created_at    timestamptz default now()
);

create index if not exists idx_alerts_product     on alerts(product_id) where active = true;
create index if not exists idx_alerts_destination on alerts(destination);

-- ─── ALERT EVENTS (audit log) ────────────────────────────────────────────────
create table if not exists alert_events (
  id          bigserial primary key,
  alert_id    uuid not null references alerts(id) on delete cascade,
  product_id  uuid not null references products(id) on delete cascade,
  old_price   numeric(10,2),
  new_price   numeric(10,2) not null,
  channel     text not null,
  status      text not null check (status in ('sent','failed')),
  error_msg   text,
  sent_at     timestamptz default now()
);

create index if not exists idx_alert_events_alert   on alert_events(alert_id);
create index if not exists idx_alert_events_product on alert_events(product_id);

-- ─── ROW LEVEL SECURITY ───────────────────────────────────────────────────────
alter table products      enable row level security;
alter table price_history enable row level security;
alter table alerts        enable row level security;
alter table alert_events  enable row level security;

-- Public (anon) can read all products and price history
create policy "Public read products"
  on products for select using (true);

create policy "Public read price_history"
  on price_history for select using (true);

-- Service role has full write access
create policy "Service role manage products"
  on products for all using (auth.role() = 'service_role');

create policy "Service role manage price_history"
  on price_history for all using (auth.role() = 'service_role');

-- Anyone can create an alert (no auth required for price drop subscriptions)
create policy "Anyone can insert alert"
  on alerts for insert with check (true);

-- Users can read their own alerts via token
create policy "Token owner can read alert"
  on alerts for select using (true);  -- RLS enforced by app-layer token check

create policy "Service role manage alerts"
  on alerts for all using (auth.role() = 'service_role');

create policy "Service role manage alert_events"
  on alert_events for all using (auth.role() = 'service_role');

-- ─── HELPER VIEWS ─────────────────────────────────────────────────────────────

-- Full product view with 7-day and 30-day price history
create or replace view deals_with_history as
select
  p.*,
  ph_min.price                         as price_7d_low,
  ph_max.price                         as price_7d_high,
  ph_first.price                       as price_30d_ago,
  -- All-time low/high
  ph_alltime_low.price                 as price_alltime_low,
  ph_alltime_high.price                as price_alltime_high
from products p
left join lateral (
  select min(price) as price from price_history
  where product_id = p.id
    and scraped_at >= now() - interval '7 days'
) ph_min on true
left join lateral (
  select max(price) as price from price_history
  where product_id = p.id
    and scraped_at >= now() - interval '7 days'
) ph_max on true
left join lateral (
  select price from price_history
  where product_id = p.id
    and scraped_at >= now() - interval '30 days'
  order by scraped_at asc
  limit 1
) ph_first on true
left join lateral (
  select min(price) as price from price_history
  where product_id = p.id
) ph_alltime_low on true
left join lateral (
  select max(price) as price from price_history
  where product_id = p.id
) ph_alltime_high on true
where p.is_available = true;


-- Summary stats for the frontend stats bar
create or replace view deal_stats as
select
  count(*)                                        as total_deals,
  count(*) filter (where is_hot)                  as hot_deals,
  round(avg(discount_pct) filter (where discount_pct > 0), 1)
                                                  as avg_discount_pct,
  count(distinct retailer)                        as retailer_count,
  count(*) filter (where category = 'laptop')     as laptop_count,
  count(*) filter (where category = 'cpu')        as cpu_count,
  count(*) filter (where category = 'gpu')        as gpu_count,
  max(last_scraped)                               as last_updated
from products
where is_available = true;


-- Best deals view: top 50 by discount, for homepage
create or replace view top_deals as
select
  p.id, p.category, p.brand, p.model, p.retailer,
  p.current_price, p.original_price, p.discount_pct,
  p.rating, p.review_count, p.is_hot,
  p.image_url, p.affiliate_url, p.specs, p.tags,
  p.seller_name, p.seller_rating
from products p
where p.is_available = true
  and p.discount_pct > 0
order by p.discount_pct desc, p.rating desc nulls last
limit 50;


-- ─── SCHEDULED MAINTENANCE (pg_cron) ─────────────────────────────────────────

-- Purge price history older than 90 days
select cron.schedule(
  'purge-old-price-history',
  '0 3 * * *',
  $$delete from price_history where scraped_at < now() - interval '90 days'$$
);

-- Mark products as unavailable if not scraped in 18 hours
-- (covers a missed scrape cycle without aggressively hiding products)
select cron.schedule(
  'mark-stale-unavailable',
  '30 */6 * * *',
  $$
    update products
    set is_available = false
    where last_scraped < now() - interval '18 hours'
      and is_available = true
  $$
);

-- Re-evaluate is_hot daily (in case thresholds change)
select cron.schedule(
  'refresh-is-hot',
  '0 2 * * *',
  $$
    update products
    set is_hot = (
      discount_pct >= 20
      and coalesce(rating, 0) >= 4.3
      and is_available = true
    )
    where true
  $$
);

-- ─── SCHEMA MIGRATION (run if upgrading from v1) ──────────────────────────────
-- Only needed if you already ran the v1 schema. Skip for fresh installs.
--
-- alter table products add column if not exists seller_name   text;
-- alter table products add column if not exists seller_rating numeric(5,2);
-- alter table products add column if not exists tech_specs_raw jsonb default '{}';
-- alter table products add column if not exists feature_bullets text[];
-- create index if not exists idx_products_specs on products using gin(specs);
-- create index if not exists idx_products_tags  on products using gin(tags);
